import type { Metadata } from "next";
// import { Geist, Geist_Mono,  } from "next/font/google";

import "../globals.css";
import Navbar from "@/utils/navbar";
import MobileNav from "@/utils/mobile-nav";
import Footer from "@/utils/footer";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {/* pb-16 creates padding at the bottom so the footer doesn't cover content */}
      {/* ${manrope.className} in main makes the font available in the whole project */}
      {/* pt-14 for mobile, md:pt-18 for desktop to match Navbar height */}
      {/* font-manrope is passed from the main layout so as to make the UI consistent */}
      <main className={` flex-1 pt-14   `}>{children}</main>
      <MobileNav />
      <Footer />
    </>
  );
}
