import type { Metadata } from "next";
// import { Geist, Geist_Mono,  } from "next/font/google";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/utils/navbar";
import MobileNav from "@/utils/mobile-nav";
import Footer from "@/utils/footer";
import { cn } from "@/lib/utils";
import AuthProvider from "../../context/AuthProvider";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        plusJakartaSans.variable,
        manrope.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${plusJakartaSans.className} min-h-full flex flex-col overflow-x-hidden`}
      >
        <AuthProvider> {children}</AuthProvider>
      </body>
    </html>
  );
}
